pipeline {
    agent any
    stages {
        stage('Submit Stack') {
            steps {
            sh "aws cloudformation create-stack --stack-name demo-stack-1 --template-body file://cloudformation/ec2.yaml --region 'us-east-1'"
              }
             }
            }
            }


