pipeline {
    agent any
properties(
    [parameters(
        [choice(

            choices: ['dev', 'uat'], 
            description: 'Select environment to build',
            name: 'ENV'
        )]
        )])
    stages {
        stage('Submit Stack') {
            steps {
            sh "selected envirnment ${choices}"
            sh "aws cloudformation create-stack --stack-name demo-stack-2 --template-body file://cloudformation/s3.json --region 'us-east-1'"
            }
         }
    }
}      
